//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ETNA.Domain;
    
    public partial class ETNADbModelContainer : DbContext
    {
        public ETNADbModelContainer()
            : base("name=ETNADbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DocumentoReferencia> DocumentosReferencia { get; set; }
        public DbSet<Almacen> Almacenes { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Empleado> Empleados { get; set; }
        public DbSet<Producto> Productos { get; set; }
        public DbSet<SolicitudEntrada> SolicitudesEntrada { get; set; }
        public DbSet<DetalleSolicitudEntrada> DetalleSolicitudEntrada { get; set; }
        public DbSet<Kardex> Kardex { get; set; }
        public DbSet<Lote> LoteSet { get; set; }
        public DbSet<TipoLote> TipoLoteSet { get; set; }
        public DbSet<SolicitudSalida> SolicitudSalidaConjunto { get; set; }
        public DbSet<DetalleSolicitudSalida> DetalleSolicitudSalidaConjunto { get; set; }
        public DbSet<DetalleGuiaSalida> DetalleGuiaSalidaConjunto { get; set; }
        public DbSet<Vehiculo> Vehiculos { get; set; }
        public DbSet<SolicitudInsumo> SolicitudInsumoSet { get; set; }
        public DbSet<DetalleSolicitudInsumo> DetalleSolicitudInsumoSet { get; set; }
        public DbSet<DetalleParteProduccionBateria> DetalleParteProduccionBateriaSet { get; set; }
        public DbSet<Bateria> BateriaSet { get; set; }
        public DbSet<DetalleOrdenTrabajoInsumo> DetalleOrdenTrabajoInsumoSet { get; set; }
        public DbSet<ParteProduccion> ParteProduccionSet { get; set; }
        public DbSet<DetalleParteProduccionInsumo> DetalleParteProduccionInsumoSet { get; set; }
        public DbSet<OrdenTrabajo> OrdenTrabajoSet { get; set; }
        public DbSet<DetalleOrdenTrabajoPersonal> DetalleOrdenTrabajoPersonalSet { get; set; }
        public DbSet<SolicitudProduccion> SolicitudProduccionSet { get; set; }
        public DbSet<PlanProduccion> PlanProduccionSet { get; set; }
        public DbSet<ProgramacionProduccion> ProgramacionProduccionSet { get; set; }
        public DbSet<DetalleSolicitudProduccion> DetalleSolicitudProduccionSet { get; set; }
        public DbSet<DetalleOrdenTrabajoMaquinaria> DetalleOrdenTrabajoMaquinariaSet { get; set; }
        public DbSet<Maquinaria> MaquinariaSet { get; set; }
        public DbSet<Backorder> Backorder { get; set; }
        public DbSet<Bateria1> Bateria1Set { get; set; }
        public DbSet<Calendario> Calendario { get; set; }
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<DetalleOrdenTrabajoInsumo1> DetalleOrdenTrabajoInsumo1Set { get; set; }
        public DbSet<DetalleOrdenTrabajoPersonal1> DetalleOrdenTrabajoPersonal1Set { get; set; }
        public DbSet<DetalleParteProduccionBateria1> DetalleParteProduccionBateria1Set { get; set; }
        public DbSet<DetalleParteProduccionInsumo1> DetalleParteProduccionInsumo1Set { get; set; }
        public DbSet<DetalleSolicitudInsumo1> DetalleSolicitudInsumo1Set { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<DisponibilidadRecurso> DisponibilidadRecurso { get; set; }
        public DbSet<DisponibilidadTransporte> DisponibilidadTransporte { get; set; }
        public DbSet<Entrega> Entrega { get; set; }
        public DbSet<EntregaDetalle> EntregaDetalle { get; set; }
        public DbSet<EstadoCliente> EstadoCliente { get; set; }
        public DbSet<EstadoEntrega> EstadoEntrega { get; set; }
        public DbSet<EstadoFactura> EstadoFactura { get; set; }
        public DbSet<EstadoHojaRuta> EstadoHojaRuta { get; set; }
        public DbSet<EstadoHojaRutaDetalle> EstadoHojaRutaDetalle { get; set; }
        public DbSet<EstadoPedido> EstadoPedido { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<FacturaDetalle> FacturaDetalle { get; set; }
        public DbSet<FacturaEntrega> FacturaEntrega { get; set; }
        public DbSet<HojaRuta> HojaRuta { get; set; }
        public DbSet<HojaRutaDetalle> HojaRutaDetalle { get; set; }
        public DbSet<HojaRutaRecurso> HojaRutaRecurso { get; set; }
        public DbSet<Insumo> Insumo { get; set; }
        public DbSet<Lotes> Lotes { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<MotivoTraslado> MotivoTraslado { get; set; }
        public DbSet<OrdenTrabajo1> OrdenTrabajo1Set { get; set; }
        public DbSet<Parametro> Parametro { get; set; }
        public DbSet<ParteProduccion1> ParteProduccion1Set { get; set; }
        public DbSet<Pedido> Pedido { get; set; }
        public DbSet<PedidoDetalle> PedidoDetalle { get; set; }
        public DbSet<PedidoEntrega> PedidoEntrega { get; set; }
        public DbSet<ProductoBackOrder> ProductoBackOrder { get; set; }
        public DbSet<SolicitudInsumo1> SolicitudInsumo1Set { get; set; }
        public DbSet<TipoCliente> TipoCliente { get; set; }
        public DbSet<TipoDireccion> TipoDireccion { get; set; }
        public DbSet<TipoDocumento> TipoDocumento { get; set; }
        public DbSet<TipoLotes> TipoLotes { get; set; }
        public DbSet<TipoPedido> TipoPedido { get; set; }
        public DbSet<TipoTransporte> TipoTransporte { get; set; }
        public DbSet<Transporte> Transporte { get; set; }
        public DbSet<Ubigeo> Ubigeo { get; set; }
        public DbSet<ZonaDespacho> ZonaDespacho { get; set; }
        public DbSet<Bateria2> Bateria2Set { get; set; }
        public DbSet<DetalleOrdenTrabajoInsumo2> DetalleOrdenTrabajoInsumo2Set { get; set; }
        public DbSet<DetalleOrdenTrabajoPersonal2> DetalleOrdenTrabajoPersonal2Set { get; set; }
        public DbSet<DetalleParteProduccionBateria2> DetalleParteProduccionBateria2Set { get; set; }
        public DbSet<DetalleParteProduccionInsumo2> DetalleParteProduccionInsumo2Set { get; set; }
        public DbSet<DetalleSolicitudInsumo2> DetalleSolicitudInsumo2Set { get; set; }
        public DbSet<OrdenTrabajo2> OrdenTrabajo2Set { get; set; }
        public DbSet<ParteProduccion2> ParteProduccion2Set { get; set; }
        public DbSet<SolicitudInsumo2> SolicitudInsumo2Set { get; set; }
    }
}
