//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.DocumentoReferencia = new HashSet<DocumentoReferencia>();
            this.Empleado = new HashSet<Empleado>();
            this.Kardex = new HashSet<Kardex>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Tipo { get; set; }
        public int AreaEnM2 { get; set; }
    
        public virtual ICollection<DocumentoReferencia> DocumentoReferencia { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
    }
}
