//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.DocumentoReferencia = new HashSet<DocumentoReferencia>();
            this.Empleado = new HashSet<Empleado>();
            this.Kardex = new HashSet<Kardex>();
            this.StockProducto = new HashSet<StockProducto>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Tipo { get; set; }
        public int AreaEnM2 { get; set; }
    
        public virtual ICollection<DocumentoReferencia> DocumentoReferencia { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual ICollection<StockProducto> StockProducto { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}
