//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backorder
    {
        public Backorder()
        {
            this.ProductoBackOrder = new HashSet<ProductoBackOrder>();
        }
    
        public int Codigo { get; set; }
        public int idEntrega { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
    
        public virtual Entrega Entrega { get; set; }
        public virtual ICollection<ProductoBackOrder> ProductoBackOrder { get; set; }
    }
}
