//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bateria2
    {
        public Bateria2()
        {
            this.DetalleParteProduccionBateria = new HashSet<DetalleParteProduccionBateria2>();
        }
    
        public int Id { get; set; }
        public string numeroSerie { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<DetalleParteProduccionBateria2> DetalleParteProduccionBateria { get; set; }
    }
}
