//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public Calendario()
        {
            this.DisponibilidadRecurso = new HashSet<DisponibilidadRecurso>();
            this.DisponibilidadTransporte = new HashSet<DisponibilidadTransporte>();
            this.HojaRutaRecurso = new HashSet<HojaRutaRecurso>();
        }
    
        public int Codigo { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
    
        public virtual ICollection<DisponibilidadRecurso> DisponibilidadRecurso { get; set; }
        public virtual ICollection<DisponibilidadTransporte> DisponibilidadTransporte { get; set; }
        public virtual ICollection<HojaRutaRecurso> HojaRutaRecurso { get; set; }
    }
}
