//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public Calendario()
        {
            this.DisponibilidadRecurso = new HashSet<DisponibilidadRecurso>();
            this.DisponibilidadTransporte = new HashSet<DisponibilidadTransporte>();
            this.HojaRutaRecurso = new HashSet<HojaRutaRecurso>();
        }
    
        public int Codigo { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
    
        public virtual ICollection<DisponibilidadRecurso> DisponibilidadRecurso { get; set; }
        public virtual ICollection<DisponibilidadTransporte> DisponibilidadTransporte { get; set; }
        public virtual ICollection<HojaRutaRecurso> HojaRutaRecurso { get; set; }
    }
}
