//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Entrega = new HashSet<Entrega>();
            this.Factura = new HashSet<Factura>();
            this.HojaRutaDetalle = new HashSet<HojaRutaDetalle>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Devolucion { get; set; }
        public string NumeroDocumento { get; set; }
        public string Renovacion { get; set; }
        public Nullable<decimal> Aceptacion { get; set; }
        public Nullable<decimal> ToleranciaFalta { get; set; }
        public Nullable<int> PrioridadReposicion { get; set; }
        public int IdTipoCliente { get; set; }
        public int idEstadoCliente { get; set; }
        public int idTipoDocumento { get; set; }
    
        public virtual EstadoCliente EstadoCliente { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Entrega> Entrega { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<HojaRutaDetalle> HojaRutaDetalle { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
