//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleParteProduccionBateria1
    {
        public int Id { get; set; }
        public int cantidadPropuesta { get; set; }
        public int cantidadReal { get; set; }
        public int ParteProduccion_Id { get; set; }
        public int Bateria_Id { get; set; }
    
        public virtual Bateria1 Bateria { get; set; }
        public virtual ParteProduccion1 ParteProduccion { get; set; }
    }
}
