//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitudSalida
    {
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public int IdSolicitudSalida { get; set; }
        public int CantidadFinal { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual SolicitudSalida SolicitudSalida { get; set; }
    }
}
