//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitudInsumo2
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public int InsumoId { get; set; }
        public int SolicitudInsumo_Id { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual SolicitudInsumo2 SolicitudInsumo { get; set; }
    }
}
