//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePlanProduccion
    {
        public int IdPlan { get; set; }
        public int IdLinea { get; set; }
        public int IdProducto { get; set; }
        public int CantidaRequerida { get; set; }
        public int Estado { get; set; }
    
        public virtual PlanProduccion PlanProduccion { get; set; }
        public virtual LineaProduccion LineaProduccion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
