//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Direccion()
        {
            this.Entrega = new HashSet<Entrega>();
            this.Factura = new HashSet<Factura>();
            this.HojaRutaDetalle = new HashSet<HojaRutaDetalle>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Codigo { get; set; }
        public string Direccion1 { get; set; }
        public string Descripcion { get; set; }
        public int idCliente { get; set; }
        public int idTipoDireccion { get; set; }
        public int idZonaDespacho { get; set; }
        public string idUbigeo { get; set; }
        public string Direccion11 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        public virtual ZonaDespacho ZonaDespacho { get; set; }
        public virtual ICollection<Entrega> Entrega { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<HojaRutaDetalle> HojaRutaDetalle { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
