//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisponibilidadRecurso
    {
        public int idCalendario { get; set; }
        public int idEmpleado { get; set; }
        public string Disponible { get; set; }
    
        public virtual Calendario Calendario { get; set; }
        public virtual Empleado Empleados { get; set; }
    }
}
