//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoReferencia
    {
        public DocumentoReferencia()
        {
            this.Kardex = new HashSet<Kardex>();
        }
    
        public int Id { get; set; }
        public string IdentificadorDocumento { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
    }
}
