//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaDetalle
    {
        public EntregaDetalle()
        {
            this.FacturaEntrega = new HashSet<FacturaEntrega>();
            this.PedidoEntrega = new HashSet<PedidoEntrega>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> NroItem { get; set; }
        public Nullable<int> CantidadEntregaProg { get; set; }
        public Nullable<int> CantidadEntregada { get; set; }
        public Nullable<int> CantidadRechazada { get; set; }
        public Nullable<int> CantidadEmbarcada { get; set; }
        public Nullable<int> CantidadConfirmada { get; set; }
        public int idEntrega { get; set; }
        public int idProducto { get; set; }
    
        public virtual Entrega Entrega { get; set; }
        public virtual Producto Productos { get; set; }
        public virtual ICollection<FacturaEntrega> FacturaEntrega { get; set; }
        public virtual ICollection<PedidoEntrega> PedidoEntrega { get; set; }
    }
}
