//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int Codigo { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<decimal> ValorBruto { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> ValorIGV { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public int idCliente { get; set; }
        public int idEstadoFactura { get; set; }
        public int idDireccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoFactura EstadoFactura { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
    }
}
