//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEntrega
    {
        public int idFacturaDetalle { get; set; }
        public int idEntregaDetalle { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual EntregaDetalle EntregaDetalle { get; set; }
        public virtual FacturaDetalle FacturaDetalle { get; set; }
    }
}
