//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public FacturaDetalle()
        {
            this.FacturaEntrega = new HashSet<FacturaEntrega>();
        }
    
        public int idFacturaDetalle { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> NroItem { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadEntregada { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public int idFactura { get; set; }
        public int idProducto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Productos { get; set; }
        public virtual ICollection<FacturaEntrega> FacturaEntrega { get; set; }
    }
}
