//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEntrega
    {
        public int idFacturaDetalle { get; set; }
        public int idEntregaDetalle { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual EntregaDetalle EntregaDetalle { get; set; }
        public virtual FacturaDetalle FacturaDetalle { get; set; }
    }
}
