//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaSalida : DocumentoReferencia
    {
        public GuiaSalida()
        {
            this.DetalleGuiaSalida = new HashSet<DetalleGuiaSalida>();
        }
    
    
        public virtual SolicitudSalida SolicitudSalida { get; set; }
        public virtual ICollection<DetalleGuiaSalida> DetalleGuiaSalida { get; set; }
    }
}
