//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaRuta
    {
        public HojaRuta()
        {
            this.HojaRutaDetalle = new HashSet<HojaRutaDetalle>();
            this.HojaRutaRecurso = new HashSet<HojaRutaRecurso>();
        }
    
        public int Codigo { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaHojaRuta { get; set; }
        public int idEstadoHojaRuta { get; set; }
        public int idZonaDespacho { get; set; }
        public Nullable<int> idTransporte { get; set; }
    
        public virtual EstadoHojaRuta EstadoHojaRuta { get; set; }
        public virtual Transporte Transporte { get; set; }
        public virtual ZonaDespacho ZonaDespacho { get; set; }
        public virtual ICollection<HojaRutaDetalle> HojaRutaDetalle { get; set; }
        public virtual ICollection<HojaRutaRecurso> HojaRutaRecurso { get; set; }
    }
}
