//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaRutaDetalle
    {
        public int idHojaRutaDetalle { get; set; }
        public Nullable<int> NroItem { get; set; }
        public Nullable<decimal> Cubicaje { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<System.DateTime> FechaUltimoEstado { get; set; }
        public int idEstadoHojaRutaDetalle { get; set; }
        public int idHojaRuta { get; set; }
        public int idCliente { get; set; }
        public int idDireccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoHojaRutaDetalle EstadoHojaRutaDetalle { get; set; }
        public virtual HojaRuta HojaRuta { get; set; }
    }
}
