//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaRutaRecurso
    {
        public int idRecurso { get; set; }
        public int idHojaRuta { get; set; }
        public int idCalendario { get; set; }
        public string Disponibilidad { get; set; }
    
        public virtual Calendario Calendario { get; set; }
        public virtual HojaRuta HojaRuta { get; set; }
    }
}
