//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        public Insumo()
        {
            this.DetalleOrdenTrabajoInsumo = new HashSet<DetalleOrdenTrabajoInsumo1>();
            this.DetalleParteProduccionInsumo = new HashSet<DetalleParteProduccionInsumo1>();
            this.DetalleSolicitudInsumo = new HashSet<DetalleSolicitudInsumo1>();
            this.DetalleOrdenTrabajoInsumo1 = new HashSet<DetalleOrdenTrabajoInsumo2>();
            this.DetalleParteProduccionInsumo1 = new HashSet<DetalleParteProduccionInsumo2>();
            this.DetalleSolicitudInsumo1 = new HashSet<DetalleSolicitudInsumo2>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int StockDisponible { get; set; }
        public int StockReservado { get; set; }
        public string Comentario { get; set; }
    
        public virtual ICollection<DetalleOrdenTrabajoInsumo1> DetalleOrdenTrabajoInsumo { get; set; }
        public virtual ICollection<DetalleParteProduccionInsumo1> DetalleParteProduccionInsumo { get; set; }
        public virtual ICollection<DetalleSolicitudInsumo1> DetalleSolicitudInsumo { get; set; }
        public virtual ICollection<DetalleOrdenTrabajoInsumo2> DetalleOrdenTrabajoInsumo1 { get; set; }
        public virtual ICollection<DetalleParteProduccionInsumo2> DetalleParteProduccionInsumo1 { get; set; }
        public virtual ICollection<DetalleSolicitudInsumo2> DetalleSolicitudInsumo1 { get; set; }
    }
}
