//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public Inventario()
        {
            this.Empleado = new HashSet<Empleado>();
            this.DetalleInventario = new HashSet<DetalleInventario>();
        }
    
        public int Id { get; set; }
        public string FechaProgramacion { get; set; }
        public string TipoInventario { get; set; }
        public string EstadoInventario { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual Almacen Almacen { get; set; }
        public virtual ICollection<DetalleInventario> DetalleInventario { get; set; }
    }
}
