//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int Id { get; set; }
        public int TipoMovimiento { get; set; }
        public string Cantidad { get; set; }
        public double ValorUnitario { get; set; }
    
        public virtual DocumentoReferencia DocumentoReferencia { get; set; }
        public virtual Almacen Almacen { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
