//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaProduccion
    {
        public LineaProduccion()
        {
            this.PlanProduccionPersonal = new HashSet<PlanProduccionPersonal>();
            this.PlanProduccionInsumo = new HashSet<PlanProduccionInsumo>();
            this.PlanProduccionMaquinaria = new HashSet<PlanProduccionMaquinaria>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
            this.DetallePlanProduccion = new HashSet<DetallePlanProduccion>();
        }
    
        public int IdLinea { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<PlanProduccionPersonal> PlanProduccionPersonal { get; set; }
        public virtual ICollection<PlanProduccionInsumo> PlanProduccionInsumo { get; set; }
        public virtual ICollection<PlanProduccionMaquinaria> PlanProduccionMaquinaria { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ICollection<DetallePlanProduccion> DetallePlanProduccion { get; set; }
    }
}
