//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaProduccion
    {
        public LineaProduccion()
        {
            this.PlanProduccionPersonal = new HashSet<PlanProduccionPersonal>();
            this.PlanProduccionInsumo = new HashSet<PlanProduccionInsumo>();
            this.PlanProduccionMaquinaria = new HashSet<PlanProduccionMaquinaria>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
            this.DetallePlanProduccion = new HashSet<DetallePlanProduccion>();
        }
    
        public int IdLinea { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<PlanProduccionPersonal> PlanProduccionPersonal { get; set; }
        public virtual ICollection<PlanProduccionInsumo> PlanProduccionInsumo { get; set; }
        public virtual ICollection<PlanProduccionMaquinaria> PlanProduccionMaquinaria { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ICollection<DetallePlanProduccion> DetallePlanProduccion { get; set; }
    }
}
