//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public int Id { get; set; }
        public string NroLote { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoLote_Id { get; set; }
        public Nullable<int> CantidadFabricada { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual TipoLotes TipoLotes { get; set; }
    }
}
