//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public Lote()
        {
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
        }
    
        public int Id { get; set; }
        public string NroLote { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual SolicitudProduccion SolicitudProduccion { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
    }
}
