//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteProduccion
    {
        public int IdLote { get; set; }
        public int IdOrden { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public int CantidadSolicitada { get; set; }
        public int CantidadFabricada { get; set; }
        public int Estado { get; set; }
    
        public virtual SolicitudProduccion SolicitudProduccion { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
