//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public int Id { get; set; }
        public string NroLote { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoLote_Id { get; set; }
        public Nullable<int> CantidadFabricada { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual TipoLotes TipoLotes { get; set; }
    }
}
