//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteProduccion
    {
        public int IdLote { get; set; }
        public string IdOrden { get; set; }
        public string FechaInicio { get; set; }
        public string FechaTermino { get; set; }
        public string CantidadSolicitada { get; set; }
        public string CantidadFabricada { get; set; }
        public string Estado { get; set; }
    
        public virtual SolicitudProduccion SolicitudProduccion { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
