//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquinaria
    {
        public Maquinaria()
        {
            this.PlanProduccionMaquinaria = new HashSet<PlanProduccionMaquinaria>();
            this.OrdenTrabajoMaquinaria = new HashSet<OrdenTrabajoMaquinaria>();
        }
    
        public int IdMaquinaria { get; set; }
        public string Descripcion { get; set; }
        public int Tipo { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<PlanProduccionMaquinaria> PlanProduccionMaquinaria { get; set; }
        public virtual ICollection<OrdenTrabajoMaquinaria> OrdenTrabajoMaquinaria { get; set; }
    }
}
