//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo1
    {
        public OrdenTrabajo1()
        {
            this.DetalleOrdenTrabajoInsumo = new HashSet<DetalleOrdenTrabajoInsumo1>();
            this.DetalleOrdenTrabajoPersonal = new HashSet<DetalleOrdenTrabajoPersonal1>();
            this.ParteProduccion = new HashSet<ParteProduccion1>();
            this.SolicitudInsumo = new HashSet<SolicitudInsumo1>();
        }
    
        public int Id { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> FechaExpedicion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public int CantidadSolicitada { get; set; }
        public string Estado { get; set; }
        public int Empleado_Id { get; set; }
        public int Lote_Id { get; set; }
    
        public virtual ICollection<DetalleOrdenTrabajoInsumo1> DetalleOrdenTrabajoInsumo { get; set; }
        public virtual ICollection<DetalleOrdenTrabajoPersonal1> DetalleOrdenTrabajoPersonal { get; set; }
        public virtual ICollection<ParteProduccion1> ParteProduccion { get; set; }
        public virtual ICollection<SolicitudInsumo1> SolicitudInsumo { get; set; }
    }
}
