//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        public OrdenTrabajo()
        {
            this.DetalleSolicitudProduccion = new HashSet<DetalleSolicitudProduccion>();
            this.DetalleOrdenTrabajoPersonal = new HashSet<DetalleOrdenTrabajoPersonal>();
            this.DetalleOrdenTrabajoInsumo = new HashSet<DetalleOrdenTrabajoInsumo>();
            this.DetalleOrdenTrabajoMaquinaria = new HashSet<DetalleOrdenTrabajoMaquinaria>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<DetalleSolicitudProduccion> DetalleSolicitudProduccion { get; set; }
        public virtual ICollection<DetalleOrdenTrabajoPersonal> DetalleOrdenTrabajoPersonal { get; set; }
        public virtual ICollection<DetalleOrdenTrabajoInsumo> DetalleOrdenTrabajoInsumo { get; set; }
        public virtual Lote Lote { get; set; }
        public virtual ICollection<DetalleOrdenTrabajoMaquinaria> DetalleOrdenTrabajoMaquinaria { get; set; }
        public virtual SolicitudInsumo SolicitudInsumo { get; set; }
    }
}
