//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajoInsumo
    {
        public int IdOrden { get; set; }
        public string IdLinea { get; set; }
        public string IdProducto { get; set; }
        public string FechaEntrega { get; set; }
        public string Cantidad { get; set; }
        public string Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
