//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajoPersonal
    {
        public int IdOrden { get; set; }
        public int IdLinea { get; set; }
        public int IdPersonal { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public int Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
