//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int idParametro { get; set; }
        public Nullable<int> PrioridadSede { get; set; }
        public Nullable<int> PlazoMaxDespacho { get; set; }
        public string TipoDistribucionStock { get; set; }
        public Nullable<int> RedondeoCubicaje { get; set; }
    }
}
