//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int idParametro { get; set; }
        public Nullable<int> PrioridadSede { get; set; }
        public Nullable<int> PlazoMaxDespacho { get; set; }
        public string TipoDistribucionStock { get; set; }
        public Nullable<int> RedondeoCubicaje { get; set; }
    }
}
