//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteProduccion1
    {
        public ParteProduccion1()
        {
            this.DetalleParteProduccionBateria = new HashSet<DetalleParteProduccionBateria1>();
            this.DetalleParteProduccionInsumo = new HashSet<DetalleParteProduccionInsumo1>();
        }
    
        public int Id { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
        public int CantidadProducida { get; set; }
        public string Comentario { get; set; }
        public int Empleado_Id { get; set; }
        public int OrdenTrabajo_Id { get; set; }
    
        public virtual ICollection<DetalleParteProduccionBateria1> DetalleParteProduccionBateria { get; set; }
        public virtual ICollection<DetalleParteProduccionInsumo1> DetalleParteProduccionInsumo { get; set; }
        public virtual OrdenTrabajo1 OrdenTrabajo { get; set; }
    }
}
