//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteProduccion2
    {
        public ParteProduccion2()
        {
            this.DetalleParteProduccionBateria = new HashSet<DetalleParteProduccionBateria2>();
            this.DetalleParteProduccionInsumo = new HashSet<DetalleParteProduccionInsumo2>();
        }
    
        public int Id { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
        public int CantidadProducida { get; set; }
        public string Comentario { get; set; }
        public int Empleado_Id { get; set; }
        public int OrdenTrabajo_Id { get; set; }
    
        public virtual ICollection<DetalleParteProduccionBateria2> DetalleParteProduccionBateria { get; set; }
        public virtual ICollection<DetalleParteProduccionInsumo2> DetalleParteProduccionInsumo { get; set; }
        public virtual OrdenTrabajo2 OrdenTrabajo { get; set; }
    }
}
