//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteProduccion
    {
        public int IdParte { get; set; }
        public int IdOrden { get; set; }
        public int IdProducto { get; set; }
        public string Glosa { get; set; }
        public System.DateTime FechaFabricacion { get; set; }
        public int CantidadProducida { get; set; }
        public string Comentario { get; set; }
        public int Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
