//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteProduccion
    {
        public int IdParte { get; set; }
        public int IdOrden { get; set; }
        public int IdProducto { get; set; }
        public string Glosa { get; set; }
        public System.DateTime FechaFabricacion { get; set; }
        public int CantidadProducida { get; set; }
        public string Comentario { get; set; }
        public int Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
