//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle
    {
        public PedidoDetalle()
        {
            this.PedidoEntrega = new HashSet<PedidoEntrega>();
        }
    
        public int idPedidoDetalle { get; set; }
        public Nullable<int> NroItem { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadEntregada { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int idPedido { get; set; }
        public int idProducto { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Productos { get; set; }
        public virtual ICollection<PedidoEntrega> PedidoEntrega { get; set; }
    }
}
