//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle
    {
        public PedidoDetalle()
        {
            this.PedidoEntrega = new HashSet<PedidoEntrega>();
        }
    
        public int idPedidoDetalle { get; set; }
        public Nullable<int> NroItem { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadEntregada { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int idPedido { get; set; }
        public int idProducto { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Productos { get; set; }
        public virtual ICollection<PedidoEntrega> PedidoEntrega { get; set; }
    }
}
