//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoEntrega
    {
        public int idEntregaDetalle { get; set; }
        public int idPedidoDetalle { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual EntregaDetalle EntregaDetalle { get; set; }
        public virtual PedidoDetalle PedidoDetalle { get; set; }
    }
}
