//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }
    
        public int Codigo { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<decimal> ValorBruto { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> ValorIGV { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public int idCliente { get; set; }
        public int idEstadoPedido { get; set; }
        public int idTipoPedido { get; set; }
        public int idDireccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
    }
}
