//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduccionPersonal
    {
        public int IdProgramacion { get; set; }
        public int IdPlan { get; set; }
        public int IdLinea { get; set; }
        public int IdPersonal { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public int Estado { get; set; }
    
        public virtual PlanProduccion PlanProduccion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual LineaProduccion LineaProduccion { get; set; }
    }
}
