//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduccion
    {
        public PlanProduccion()
        {
            this.PlanProduccionMaquinaria = new HashSet<PlanProduccionMaquinaria>();
            this.PlanProduccionInsumo = new HashSet<PlanProduccionInsumo>();
            this.PlanProduccionPersonal = new HashSet<PlanProduccionPersonal>();
            this.DetallePlanProduccion = new HashSet<DetallePlanProduccion>();
        }
    
        public int IdPlan { get; set; }
        public int IdProducto { get; set; }
        public string Glosa { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPlan { get; set; }
        public int UnidadesProducir { get; set; }
        public int TotalHorasMaquinaria { get; set; }
        public int TotalCantidadMaquinaria { get; set; }
        public int TotalCantidadInsumo { get; set; }
    
        public virtual ICollection<PlanProduccionMaquinaria> PlanProduccionMaquinaria { get; set; }
        public virtual ICollection<PlanProduccionInsumo> PlanProduccionInsumo { get; set; }
        public virtual ICollection<PlanProduccionPersonal> PlanProduccionPersonal { get; set; }
        public virtual SolicitudProduccion SolicitudProduccion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<DetallePlanProduccion> DetallePlanProduccion { get; set; }
    }
}
