//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduccion
    {
        public PlanProduccion()
        {
            this.PlanProduccionMaquinaria = new HashSet<PlanProduccionMaquinaria>();
            this.PlanProduccionInsumo = new HashSet<PlanProduccionInsumo>();
            this.PlanProduccionPersonal = new HashSet<PlanProduccionPersonal>();
            this.DetallePlanProduccion = new HashSet<DetallePlanProduccion>();
        }
    
        public int IdPlan { get; set; }
        public int IdProducto { get; set; }
        public string Glosa { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPlan { get; set; }
        public int UnidadesProducir { get; set; }
        public int TotalHorasMaquinaria { get; set; }
        public int TotalCantidadMaquinaria { get; set; }
        public int TotalCantidadInsumo { get; set; }
    
        public virtual ICollection<PlanProduccionMaquinaria> PlanProduccionMaquinaria { get; set; }
        public virtual ICollection<PlanProduccionInsumo> PlanProduccionInsumo { get; set; }
        public virtual ICollection<PlanProduccionPersonal> PlanProduccionPersonal { get; set; }
        public virtual SolicitudProduccion SolicitudProduccion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<DetallePlanProduccion> DetallePlanProduccion { get; set; }
    }
}
