//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduccionMaquinaria
    {
        public int IdProgramacion { get; set; }
        public string IdPlan { get; set; }
        public string IdLinea { get; set; }
        public string IdMaquinaria { get; set; }
        public string FechaInicio { get; set; }
        public string FechaTermino { get; set; }
        public string Cantidad { get; set; }
        public string Estado { get; set; }
    
        public virtual PlanProduccion PlanProduccion { get; set; }
        public virtual Maquinaria Maquinaria { get; set; }
        public virtual LineaProduccion LineaProduccion { get; set; }
    }
}
