//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.SolicitudEntradaProducto = new HashSet<DetalleSolicitudEntrada>();
            this.Kardex = new HashSet<Kardex>();
            this.DetalleSolicitudSalida = new HashSet<DetalleSolicitudSalida>();
            this.DetalleGuiaSalida = new HashSet<DetalleGuiaSalida>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public double PrecioListaCompra { get; set; }
        public double PrecioListaVenta { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<DetalleSolicitudEntrada> SolicitudEntradaProducto { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual ICollection<DetalleSolicitudSalida> DetalleSolicitudSalida { get; set; }
        public virtual ICollection<DetalleGuiaSalida> DetalleGuiaSalida { get; set; }
    }
}
