//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoBackOrder
    {
        public int idProducto { get; set; }
        public int idBackorder { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Backorder Backorder { get; set; }
        public virtual Producto Productos { get; set; }
    }
}
