//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.SolicitudEntradaProducto = new HashSet<DetalleSolicitudEntrada>();
            this.Kardex = new HashSet<Kardex>();
            this.DetalleSolicitudSalida = new HashSet<DetalleSolicitudSalida>();
            this.DetalleGuiaSalida = new HashSet<DetalleGuiaSalida>();
            this.EntregaDetalle = new HashSet<EntregaDetalle>();
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
            this.ProductoBackOrder = new HashSet<ProductoBackOrder>();
            this.StockProducto = new HashSet<StockProducto>();
            this.DetalleInventario = new HashSet<DetalleInventario>();
            this.PlanProduccionInsumo = new HashSet<PlanProduccionInsumo>();
            this.OrdenTrabajoInsumo = new HashSet<OrdenTrabajoInsumo>();
            this.ParteProduccion = new HashSet<ParteProduccion>();
            this.DetallePlanProduccion = new HashSet<DetallePlanProduccion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public double PrecioListaCompra { get; set; }
        public double PrecioListaVenta { get; set; }
        public int Estado { get; set; }
        public string Numero { get; set; }
        public Nullable<int> Vigencia { get; set; }
        public string UnidadTiempoVigencia { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string UnidadDimensiones { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string UnidadPeso { get; set; }
    
        public virtual ICollection<DetalleSolicitudEntrada> SolicitudEntradaProducto { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual ICollection<DetalleSolicitudSalida> DetalleSolicitudSalida { get; set; }
        public virtual ICollection<DetalleGuiaSalida> DetalleGuiaSalida { get; set; }
        public virtual ICollection<EntregaDetalle> EntregaDetalle { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
        public virtual ICollection<ProductoBackOrder> ProductoBackOrder { get; set; }
        public virtual ICollection<StockProducto> StockProducto { get; set; }
        public virtual ICollection<DetalleInventario> DetalleInventario { get; set; }
        public virtual ICollection<PlanProduccionInsumo> PlanProduccionInsumo { get; set; }
        public virtual ICollection<OrdenTrabajoInsumo> OrdenTrabajoInsumo { get; set; }
        public virtual ICollection<ParteProduccion> ParteProduccion { get; set; }
        public virtual PlanProduccion PlanProduccion { get; set; }
        public virtual ICollection<DetallePlanProduccion> DetallePlanProduccion { get; set; }
    }
}
