//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.SolicitudEntradaProducto = new HashSet<DetalleSolicitudEntrada>();
            this.Kardex = new HashSet<Kardex>();
            this.DetalleSolicitudSalida = new HashSet<DetalleSolicitudSalida>();
            this.DetalleGuiaSalida = new HashSet<DetalleGuiaSalida>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public double PrecioListaCompra { get; set; }
        public double PrecioListaVenta { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<DetalleSolicitudEntrada> SolicitudEntradaProducto { get; set; }
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual ICollection<DetalleSolicitudSalida> DetalleSolicitudSalida { get; set; }
        public virtual ICollection<DetalleGuiaSalida> DetalleGuiaSalida { get; set; }
    }
}
