//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudSalida
    {
        public SolicitudSalida()
        {
            this.GuiaSalida = new HashSet<GuiaSalida>();
            this.DetalleSolicitudSalida = new HashSet<DetalleSolicitudSalida>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public string DireccionEntrega { get; set; }
        public string RazonSocialDestinatario { get; set; }
        public int TipoSalida { get; set; }
        public int Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual ICollection<GuiaSalida> GuiaSalida { get; set; }
        public virtual ICollection<DetalleSolicitudSalida> DetalleSolicitudSalida { get; set; }
    }
}
