//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudReprogramacion
    {
        public int IdReprogramacion { get; set; }
        public int IdOrden { get; set; }
        public string Motivo { get; set; }
        public int Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
