//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudInsumo2
    {
        public SolicitudInsumo2()
        {
            this.DetalleSolicitudInsumo = new HashSet<DetalleSolicitudInsumo2>();
        }
    
        public int Id { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
        public int Empleado_Id { get; set; }
        public int OrdenTrabajo_Id { get; set; }
    
        public virtual ICollection<DetalleSolicitudInsumo2> DetalleSolicitudInsumo { get; set; }
        public virtual OrdenTrabajo2 OrdenTrabajo { get; set; }
    }
}
