//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudProduccion
    {
        public SolicitudProduccion()
        {
            this.LoteProduccion = new HashSet<LoteProduccion>();
            this.DetalleSolicitudProduccion = new HashSet<DetalleSolicitudProduccion>();
        }
    
        public int IdSolicitud { get; set; }
        public int IdPlan { get; set; }
        public string Glosa { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Observacion { get; set; }
        public int Estado { get; set; }
    
        public virtual PlanProduccion PlanProduccion { get; set; }
        public virtual ICollection<LoteProduccion> LoteProduccion { get; set; }
        public virtual ICollection<DetalleSolicitudProduccion> DetalleSolicitudProduccion { get; set; }
    }
}
