//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudEntrada
    {
        public SolicitudEntrada()
        {
            this.SolicitudEntradaProducto = new HashSet<DetalleSolicitudEntrada>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public int TipoEntrada { get; set; }
        public int Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual GuiaEntrada GuiaEntrada { get; set; }
        public virtual ICollection<DetalleSolicitudEntrada> SolicitudEntradaProducto { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
