//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTransporte
    {
        public TipoTransporte()
        {
            this.Transporte = new HashSet<Transporte>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }
    
        public virtual ICollection<Transporte> Transporte { get; set; }
    }
}
