//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public Transporte()
        {
            this.DisponibilidadTransporte = new HashSet<DisponibilidadTransporte>();
            this.HojaRuta = new HashSet<HojaRuta>();
        }
    
        public int Codigo { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public string UnidadPeso { get; set; }
        public Nullable<int> NroEjes { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public Nullable<decimal> Cubicaje { get; set; }
        public string UnidadCubicaje { get; set; }
        public int idTipoTransporte { get; set; }
        public int idMarca { get; set; }
    
        public virtual ICollection<DisponibilidadTransporte> DisponibilidadTransporte { get; set; }
        public virtual ICollection<HojaRuta> HojaRuta { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual TipoTransporte TipoTransporte { get; set; }
    }
}
