//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public Transporte()
        {
            this.DisponibilidadTransporte = new HashSet<DisponibilidadTransporte>();
            this.HojaRuta = new HashSet<HojaRuta>();
        }
    
        public int Codigo { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public string UnidadPeso { get; set; }
        public Nullable<int> NroEjes { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public Nullable<decimal> Cubicaje { get; set; }
        public string UnidadCubicaje { get; set; }
        public int idTipoTransporte { get; set; }
        public int idMarca { get; set; }
    
        public virtual ICollection<DisponibilidadTransporte> DisponibilidadTransporte { get; set; }
        public virtual ICollection<HojaRuta> HojaRuta { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual TipoTransporte TipoTransporte { get; set; }
    }
}
