//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubigeo
    {
        public Ubigeo()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
